# Docker Compose for production with security and performance optimizations

services:
  nginx:
    # Production nginx configuration
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  nmc-site:
    build:
      cache_from:
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc-site:latest
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc/cache:site-deps
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc/cache:site-build
      args:
        - BUILDKIT_INLINE_CACHE=1
        - NODE_ENV=production
    image: ${DOCKER_REGISTRY:-localhost:5000}/nmc-site:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    security_opt:
      - no-new-privileges:true
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  nmc-server:
    build:
      cache_from:
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc-server:latest
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc/cache:server-deps
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc/cache:server-build
      args:
        - BUILDKIT_INLINE_CACHE=1
        - NODE_ENV=production
    image: ${DOCKER_REGISTRY:-localhost:5000}/nmc-server:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.75'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    security_opt:
      - no-new-privileges:true
    environment:
      - NODE_ENV=production

  nmc-storybook:
    build:
      cache_from:
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc/cache:storybook-deps
        - ${DOCKER_REGISTRY:-localhost:5000}/nmc/cache:storybook-build
      args:
        - BUILDKIT_INLINE_CACHE=1
        - NODE_ENV=production

  # Remove registry from production
  registry:
    profiles:
      - never
