services:
  nginx:
    image: nginx:alpine
    container_name: nmc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/conf.d:/etc/nginx/conf.d:ro
      - storybook-static:/var/www/storybook:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - nmc-network
    depends_on:
      nmc-site:
        condition: service_healthy
      nmc-server:
        condition: service_healthy
      nmc-storybook:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nmc-site:
    build:
      context: .
      dockerfile: apps/nmc-site.v1/Dockerfile
    container_name: nmc-site
    expose:
      - "3000"
    networks:
      - nmc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  nmc-server:
    build:
      context: .
      dockerfile: apps/nmc-server.v1/Dockerfile
    container_name: nmc-server
    expose:
      - "3001"
    networks:
      - nmc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  nmc-storybook:
    build:
      context: .
      dockerfile: packages/nmc-storybook.v1/Dockerfile
      target: export
    container_name: nmc-storybook-builder
    volumes:
      - storybook-static:/output
    command: ['sh', '-c', 'cp -r /storybook-static/* /output/ && echo "Storybook build completed"']

volumes:
  storybook-static:

networks:
  nmc-network:
    driver: bridge
