version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nmc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./packages/nmc-storybook.v1/storybook-static:/var/www/storybook:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - nmc-network
    restart: unless-stopped

  nmc-site:
    build:
      context: ./apps/nmc-site.v1
      dockerfile: Dockerfile
    container_name: nmc-site
    ports:
      - "3000:3000"
    networks:
      - nmc-network
    restart: unless-stopped

  nmc-server:
    build:
      context: ./apps/nmc-server.v1
      dockerfile: Dockerfile
    container_name: nmc-server
    ports:
      - "3001:3001"
    networks:
      - nmc-network
    restart: unless-stopped

networks:
  nmc-network:
    driver: bridge
