services:
  # Simple web server serving static content and API proxy
  nginx:
    image: nginx:alpine
    container_name: nmc-nginx
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static-content:/var/www/static:ro
    restart: unless-stopped

  # Simple Node.js API server
  nmc-server:
    image: node:20-alpine
    container_name: nmc-server
    working_dir: /app
    command: ["sh", "-c", "echo 'const express = require(\"express\"); const app = express(); app.get(\"/\", (req, res) => res.json({status: \"ok\", service: \"nmc-server\"})); app.listen(3001, () => console.log(\"Server running on port 3001\"));' > server.js && npm init -y && npm install express && node server.js"]
    expose:
      - "3001"
    restart: unless-stopped

  # Simple static site
  nmc-site:
    image: nginx:alpine
    container_name: nmc-site
    volumes:
      - ./static-content:/usr/share/nginx/html:ro
    expose:
      - "80"
    restart: unless-stopped

  # Simple storybook placeholder
  nmc-storybook:
    image: nginx:alpine
    container_name: nmc-storybook
    volumes:
      - ./static-content/ui:/usr/share/nginx/html:ro
    expose:
      - "80"
    restart: unless-stopped
