name: Deploy to Server (No Docker Hub)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/nmc-core.v1 || git clone https://github.com/Nemec163/nmc-core.v1.git && cd nmc-core.v1
            git pull origin main

            echo "🔁 Building and restarting containers..."

            docker rm -f nmc-site || true
            docker rm -f nmc-server || true
            docker rm -f nmc-ui || true

            docker build -t nmc-site ./apps/nmc-site.v1
            docker build -t nmc-server ./apps/nmc-server.v1
            docker build -t nmc-ui ./packages/nmc-ui.v1

            docker run -d --name nmc-site -p 3000:3000 nmc-site
            docker run -d --name nmc-server -p 3001:3000 nmc-server
            docker run -d --name nmc-ui -p 6006:6006 nmc-ui

            systemctl restart nginx
