name: Deploy to Server (No Docker Hub)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/nmc-core.v1 || git clone https://github.com/Nemec163/nmc-core.v1.git && cd nmc-core.v1
            git pull origin main

            echo "🔁 Installing pnpm and building Storybook..."
            corepack enable
            corepack prepare pnpm@latest --activate
            pnpm install --frozen-lockfile
            pnpm --filter nmc-storybook.v1 build

            echo "📁 Copying Storybook to /var/www/storybook"
            rm -rf /var/www/storybook/*
            cp -r packages/nmc-storybook.v1/storybook-static/* /var/www/storybook/
            chown -R www-data:www-data /var/www/storybook
            chmod -R 755 /var/www/storybook

            echo "🐳 Building & restarting Docker containers..."
            docker rm -f nmc-site   || true
            docker rm -f nmc-server || true

            docker build -t nmc-site   ./apps/nmc-site.v1
            docker build -t nmc-server ./apps/nmc-server.v1

            docker run -d --name nmc-site   -p 3000:3000 nmc-site
            docker run -d --name nmc-server -p 3001:3000 nmc-server

            echo "🔁 Reloading nginx..."
            nginx -t && systemctl reload nginx
