name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm --filter nmc-storybook.v1 run build

  deploy-storybook:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync Storybook to server
        uses: burnett01/rsync-deploy@v3
        with:
          switches: -az --delete
          path: packages/nmc-storybook.v1/storybook-static/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          remote_path: /root/nmc-core.v1/packages/nmc-storybook.v1/storybook-static/

      - name: Reload nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo systemctl reload nginx
